# =====================================================================
# LSF Global Configuration - lsf.conf
# =====================================================================

LSF_CLUSTER_NAME=eda_cluster
LSF_AUTH=eauth
LSF_MASTER_LIST=master.onprem.local
LSF_SERVER_HOSTS=master.onprem.local
LSF_LIM_PORT=7869
LSF_RES_PORT=6878
LSB_MBD_PORT=6881
LSB_SBD_PORT=6882

ENABLE_DYNAMIC_HOSTS=Y
LSF_DYNAMIC_HOST_CONTROL=Y
LSF_ADD_SUB_HOSTS=Y
LSF_REG_FLOAT_HOSTS=Y
LSF_DYNAMIC_HOST_WAIT_TIME=60

# Resource Connector Settings
LSB_START_EBROKERD=Y
LSB_RC_EXTERNAL_HOST_FLAG=googlehost
LSB_RC_EXTERNAL_HOST_IDLE_TIME=2
LSB_RC_EXTERNAL_HOST_MAX_TTL=1440
LSB_DEBUG_SCH=LOG_DEBUG3
LSF_LOG_MASK=LOG_DEBUG
LSF_DEBUG_LIM=LOG_DEBUG3

LSF_CONFDIR=/opt/lsf/conf
LSB_CONFDIR=/opt/lsf/conf/lsbatch
LSF_LOGDIR=/opt/lsf/log
LSB_SHAREDIR=/opt/lsf/work
LSF_TOP=/opt/lsf
LSF_VERSION=10.1
LSF_ADMINS=lsfadmin
JAVA_HOME=/usr/lib/jvm/jre
LSF_SHELL=/bin/sh
LSF_USER_DOMAIN=onprem.local
LSF_IP_VERSION=4
LSF_ENABLE_EGO=N
LSF_EGO_DAEMON_CONTROL=N
LSF_STRIP_DOMAIN=.us-central1-a.c.lsf-testing-001.internal:.onprem.local
